apiVersion: core.kapp.dev/v1alpha1
kind: HttpsCertIssuer
metadata:
  name: default-cert-issuer
spec:
  caForTest: {}
---
apiVersion: core.kapp.dev/v1alpha1
kind: HttpsCert
metadata:
  name: default-https-cert
spec:
  httpsCertIssuer: default-cert-issuer
  isSelfManaged: false
  domains:
    - "*"
---
apiVersion: core.kapp.dev/v1alpha1
kind: HttpsCert
metadata:
  name: xip-io-cert
spec:
  httpsCertIssuer: default-cert-issuer
  isSelfManaged: false
  domains:
    - "xip.io"
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-http-route
---
apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name:  test-http-route
spec:
  isActive: true
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: server-v1
  namespace: test-http-route
spec:
  image: k8s.gcr.io/echoserver:1.10
  ports:
    - name: http
      containerPort: 8080
      servicePort: 80
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: server-v2
  namespace: test-http-route
spec:
  image: k8s.gcr.io/echoserver:1.10
  ports:
    - name: http
      containerPort: 8080
      servicePort: 80
---
apiVersion: core.kapp.dev/v1alpha1
kind: HttpRoute
metadata:
  name: v1-only-route
  namespace: test-http-route
spec:
  hosts:
    - xip.io
  methods:
    - GET
    - POST
  schemes:
    - http
    - https
  paths:
    - /v1
  destinations:
    - host: server-v1
      weight: 1
  stripPath: true
---
apiVersion: core.kapp.dev/v1alpha1
kind: HttpRoute
metadata:
  name: v2-only-route
  namespace: test-http-route
spec:
  hosts:
    - xip.io
  methods:
    - GET
    - POST
  schemes:
    - http
    - https
  paths:
    - /v2
  destinations:
    - host: server-v2
      weight: 1
  stripPath: true
---
apiVersion: core.kapp.dev/v1alpha1
kind: HttpRoute
metadata:
  name: v1-v2-canary
  namespace: test-http-route
spec:
  hosts:
    - "*.xip.io"
    - xip.io
  methods:
    - GET
    - POST
    - PUT
  schemes:
    - http
    - https
  paths:
    - /
  destinations:
    - host: server-v2
      weight: 1
    - host: server-v1
      weight: 1
  stripPath: true

