apiVersion: v1
kind: Namespace
metadata:
  name: kalm-vols
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: core.kalm.dev/v1alpha1
kind: Component
metadata:
    name: hi-sts
    namespace: kalm-vols
spec:
    image: strm/helloworld-http:latest
    workloadType: statefulset
    replicas: 2
    volumes:
      - path: /data
        size: 1Mi
        type: pvc
        storageClassName: kalm-standard
        pvc: my-pvc
      - path: /tmp
        size: 2Mi
        type: emptyDirMemory
    ports:
        - name: http
          containerPort: 80
          servicePort: 80
