apiVersion: core.kapp.dev/v1alpha1
kind: ApplicationPlugin
metadata:
  name: kapp-builtin-application-plugin-ingress
spec:
  src: |
    function AfterApplicationSaved() {
      __builtinApplicationPluginIngress();
    }
  configSchema:
    title: Ingress rules
    type: object
    required:
      - hosts
      - paths
    properties:
      hosts:
        type: array
        items:
          type: string
      paths:
        type: array
        items:
          type: string
      stripPath:
        type: boolean
      destinations:
        type: array
        items:
          type: object
          properties:
            destination:
              type: string
            weight:
              type: number

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-builtin-plugin
---
apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name: test-builtin-plugin
spec:
  isActive: true
---
apiVersion: core.kapp.dev/v1alpha1
kind: ApplicationPluginBinding
metadata:
  name: kapp-builtin-application-plugin-ingress
  namespace: test-builtin-plugin
spec:
  pluginName: kapp-builtin-application-plugin-ingress
  config:
    hosts:
      - "*"
    paths:
      - "/abc"
      - "/"
    stripPath: true
    destinations:
      - destination: server-v1
        weight: 50
      - destination: server-v2
        weight: 50
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: server-v1
  namespace: test-builtin-plugin
spec:
  image: strm/helloworld-http
  ports:
    - name: http
      containerPort: 80
      servicePort: 80
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: server-v2
  namespace: test-builtin-plugin
spec:
  image: strm/helloworld-http
  ports:
    - name: http
      containerPort: 80
      servicePort: 80