apiVersion: v1
kind: Namespace
metadata:
  name: kapp-hello-world
  labels:
    istio-injection: enabled
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
    name: hello-world
    namespace: kapp-hello-world
spec:
    image: strm/helloworld-http:latest
    ports:
        - name: http
          containerPort: 80
          servicePort: 80
---
# todo routes
