apiVersion: v1
kind: Namespace
metadata:
  name: kalm-vols
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: core.kalm.dev/v1alpha1
kind: Component
metadata:
  name: hello-world
  namespace: kalm-vols
spec:
  image: strm/helloworld-http:latest
  ports:
    - protocol: http
      containerPort: 80
      servicePort: 80
  volumes:
    - path: /tmp/foobar
      size: 1Mi
      type: pvc
      storageClassName: kalm-standard
      pvToMatch: pvc-a9849600-24bc-4f0e-8bb1-c023e62c7bdd
      pvc: pvc-data
