apiVersion: v1
kind: Namespace
metadata:
  name: kapp-socks
---
apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name: socks
  namespace: kapp-socks
spec:
  isActive: true
  components:
    - name: payment
      image: weaveworksdemos/payment:0.4.3
      replicas: 1
      cpu: 100m
      memory: 100Mi
      ports:
        - name: http
          containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 300
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 180
        periodSeconds: 3
  sharedEnv:
    - name: SOME_COMMON_ENV
      value: shared_value
