apiVersion: v1
kind: Namespace
metadata:
  name: kapp-sts
  labels:
    istio-injection: enabled
    kapp-enabled: "true"
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
    name: hello-sts
    namespace: kapp-sts
spec:
    image: strm/helloworld-http:latest
    workloadType: statefulset
    replicas: 2
    volumes:
      - path: /data
        size: 1Mi
        type: pvc
        storageClassName: kapp-standard
        persistentVolumeClaimName: my-pvc
      - path: /tmp
        size: 2Mi
        type: emptyDirMemory
    ports:
        - name: http
          containerPort: 80
          servicePort: 80
