apiVersion: v1
kind: Namespace
metadata:
  name: kalm-system
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cronjob
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: core.kalm.dev/v1alpha1
kind: Component
metadata:
  name: hello-world
  namespace: cronjob
spec:
  image: kalmhq/echoserver:latest
  workloadType: cronjob
  command: ls
  schedule: "*/5 * * * *"
