apiVersion: v1
kind: Namespace
metadata:
  name: kapp-hello-world
  labels:
    istio-injection: enabled
---
apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name: kapp-hello-world
spec:
  isActive: true
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
    name: hello-world
    namespace: kapp-hello-world
spec:
    image: strm/helloworld-http:latest
    ports:
        - name: http
          containerPort: 80
          servicePort: 80
---
apiVersion: core.kapp.dev/v1alpha1
kind: ApplicationPlugin
metadata:
  name: kapp-builtin-application-plugin-ingress
spec:
  src: |
    function AfterApplicationSaved() {
      __builtinApplicationPluginIngress();
    }
  configSchema:
    title: Ingress rules
    type: object
    required:
      - hosts
      - paths
    properties:
      hosts:
        type: array
        items:
          type: string
      httpsCert:
        type: string
      paths:
        type: array
        items:
          type: string
      stripPath:
        type: boolean
      destinations:
        type: array
        items:
          type: object
          properties:
            destination:
              type: string
            weight:
              type: number
---
apiVersion: core.kapp.dev/v1alpha1
kind: ApplicationPluginBinding
metadata:
  name: kapp-builtin-application-plugin-ingress
  namespace: kapp-hello-world
spec:
  pluginName:  kapp-builtin-application-plugin-ingress
  config:
    hosts:
      - "*"
    paths:
      - "/"
    destinations:
      - destination: hello-world:80