apiVersion: v1
kind: Namespace
metadata:
  name: kalm-kafka
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: core.kalm.dev/v1alpha1
kind: Component
metadata:
    name: kafka
    namespace: kalm-kafka
spec:
    workloadType: statefulset
    image: confluentinc/cp-kafka:5.0.1
    command: "sh -exc 'unset KAFKA_PORT && export KAFKA_BROKER_ID=${POD_NAME##*-} && export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && exec /etc/confluent/docker/run'"
    replicas: 3
    enableHeadlessService: true
    env:
      - name: POD_IP
        value: status.podIP
        type: fieldref
      - name: POD_NAME
        value: metadata.name
        type: fieldref
      - name: POD_NAMESPACE
        value: metadata.namespace
        type: fieldref
      - name: KAFKA_HEAP_OPTS
        value: -Xmx1G -Xms1G
      - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: "3"
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: zk.kalm-zk:2181
      - name: KAFKA_LOG_DIRS
        value: /opt/kafka/data/logs
      - name: KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE
        value: "false"
      - name: KAFKA_JMX_PORT
        value: "5555"
    volumes:
      - path: /opt/kafka/data
        type: pvc
        size: 512Mi
        persistentVolumeClaimName: kakfa-data
    ports:
      - name: kafka
        containerPort: 9092
        servicePort: 9092
    livenessProbe:
      exec:
        command:
          - sh
          - -ec
          - /usr/bin/jps | /bin/grep -q SupportedKafka
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: kafka
      timeoutSeconds: 5
