apiVersion: v1
kind: Namespace
metadata:
  name: kalm-system
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kalm-hello-world
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: core.kalm.dev/v1alpha1
kind: Component
metadata:
  name: hello-world
  namespace: kalm-hello-world
spec:
  image: kalmhq/echoserver:latest
  ports:
    - protocol: http
      containerPort: 8001
    - protocol: http2
      containerPort: 8002
    - protocol: https
      containerPort: 8003
    - protocol: grpc
      containerPort: 8004
---
apiVersion: core.kalm.dev/v1alpha1
kind: HttpRoute
metadata:
  name: hello-world
  namespace: kalm-hello-world
spec:
  hosts:
    - "*"
  methods:
    - GET
    - POST
  schemes:
    - http
  paths:
    - /
  destinations:
    - host: hello-world.kalm-hello-world.svc.cluster.local:8001
      weight: 1
  stripPath: true
