apiVersion: v1
kind: Namespace
metadata:
  name: kapp-vols
  labels:
    istio-injection: enabled
    kapp-enabled: "true"
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: vol-dp
  namespace: kapp-vols
spec:
  image: strm/helloworld-http:latest
  ports:
    - name: http
      containerPort: 80
      servicePort: 80
  volumes:
    - path: /tmp
      size: 2Mi
      type: emptyDirMemory
    - path: /data
      size: 1Mi
      type: pvc
      storageClassName: kapp-standard
      persistentVolumeClaimName: pvc-data
