
apiVersion: core.kalm.dev/v1alpha1
kind: ComponentPlugin
metadata:
  name: kalm-static-sacle-double
spec:
  src: |
    function BeforeDeploymentSave(deployment) {
      deployment.spec.replicas = 2;
      return deployment;
    }
  availableWorkloadType:
    - server
---
apiVersion: core.kalm.dev/v1alpha1
kind: ComponentPlugin
metadata:
  name: kalm-scale-name-with-suffix-tiple
spec:
  src: |
    function ComponentFilter(component) {
      return component.metadata.name.endsWith("tiple");
    }

    function BeforeDeploymentSave(deployment) {
      deployment.spec.replicas = 3;
      return deployment;
    }
  availableWorkloadType:
    - server
---
apiVersion: core.kalm.dev/v1alpha1
kind: ComponentPlugin
metadata:
  name: kalm-test-default-embedded-functions
spec:
  src: |
    // you will see logs in controller consoles
    function BeforeDeploymentSave(deployment) {
      console.log("getApplicationName", getApplicationName());
      console.log("getCurrentComponentName", getCurrentComponent().name);
      return deployment;
    }
---
apiVersion: core.kalm.dev/v1alpha1
kind: ComponentPlugin
metadata:
  name: kalm-customize-probes
spec:
  src: |
    function addProbesForContainer(container) {
      if (!container.readinessProbe) {
        container.readinessProbe = {};
      }

      container.readinessProbe.httpGet = {
        path: "/",
        port: 80
      };

      container.readinessProbe.initialDelaySeconds = 5;
      container.readinessProbe.timeoutSeconds = 20;
      container.readinessProbe.periodSeconds = 5;
      container.readinessProbe.successThreshold = 1;
      container.readinessProbe.failureThreshold = 3;
    }

    function AfterPodTemplateGeneration(pod) {
      var containers = pod.spec.containers;
      containers.forEach(addProbesForContainer)
      return pod;
    }
  availableWorkloadType:
    - server
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    kalm-enabled: "true"
---
apiVersion: core.kalm.dev/v1alpha1
kind: ComponentPluginBinding
metadata:
  name:  test-kalm-scale-name-with-suffix-tiple
  namespace: test
spec:
  pluginName: kalm-scale-name-with-suffix-tiple
---
apiVersion: core.kalm.dev/v1alpha1
kind: ComponentPluginBinding
metadata:
  name:  test-kalm-customize-probes
  namespace: test
spec:
  pluginName: kalm-customize-probes
---
apiVersion: core.kalm.dev/v1alpha1
kind: ComponentPluginBinding
metadata:
  name:  test-kalm-test-default-embedded-functions
  namespace: test
spec:
  pluginName: kalm-test-default-embedded-functions
---
apiVersion: core.kalm.dev/v1alpha1
kind: Component
metadata:
  name: nginx-double
  namespace: test
spec:
    image: nginx:alpine
    workloadType: server
---
apiVersion: core.kalm.dev/v1alpha1
kind: ComponentPluginBinding
metadata:
  name:  nginx-double-kalm-static-sacle-double
  namespace: test
spec:
  pluginName: kalm-static-sacle-double
  componentName: nginx-double
---
apiVersion: core.kalm.dev/v1alpha1
kind: Component
metadata:
  name: nginx-tiple
  namespace: test
spec:
  image: nginx:alpine
  workloadType: server
