apiVersion: v1
kind: Namespace
metadata:
  name: kalm-vols
  labels:
    istio-injection: enabled
    kalm-enabled: "true"
---
apiVersion: core.kalm.dev/v1alpha1
kind: Component
metadata:
  name: vol-dp
  namespace: kalm-vols
spec:
  image: strm/helloworld-http:latest
  ports:
    - name: http
      containerPort: 80
      servicePort: 80
  volumes:
    - path: /tmp
      size: 2Mi
      type: emptyDirMemory
    - path: /data
      size: 1Mi
      type: pvc
      storageClassName: kalm-standard
      pvc: pvc-data
