apiVersion: v1
kind: Namespace
metadata:
  name: kapp-hipster
  labels:
    istio-injection: enabled
---
apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name: kapp-hipster
spec:
  isActive: true
---
apiVersion: core.kapp.dev/v1alpha1
kind: Plugin
metadata:
  name: termination-grace
spec:
  src: |
    function AfterPodTemplateGeneration(pod) {
      var config = getConfig();

      if (!config) {
        return;
      }

      if (config.periodSeconds) {
        pod.spec.terminationGracePeriodSeconds = config.periodSeconds;
      }

      return pod;
    }
  configSchema:
    type: object
    properties:
      periodSeconds:
        type: number

---
apiVersion: core.kapp.dev/v1alpha1
kind: Plugin
metadata:
  name: manually-scale
spec:
  src: |
    function BeforeDeploymentSave(deployment) {
      deployment.spec.replicas = getConfig().replicas;
      return deployment;
    }
  configSchema:
    type: object
    properties:
      replicas:
        type: number
---
apiVersion: core.kapp.dev/v1alpha1
kind: Plugin
metadata:
  name: grpc-health-probe
spec:
  src: |
    function addProbesForContainer(container) {
      var config = getConfig();

      if (!config) {
        return
      }

      var command = ["/bin/grpc_health_probe", "-addr=:" + config.port];

      if (config.rpcTimeout) {
        command.push("-rpc-timeout=" + config.rpcTimeout);
      }

      container.readinessProbe = {
        exec: {
          command: command,
        }
      };

      container.livenessProbe = {
        exec: {
          command: command,
        }
      };

      if (config.initialDelaySeconds) {
        container.readinessProbe.initialDelaySeconds = config.initialDelaySeconds;
        container.livenessProbe.initialDelaySeconds = config.initialDelaySeconds;
      }

      if (config.periodSeconds) {
        container.readinessProbe.periodSeconds = config.periodSeconds;
        container.livenessProbe.periodSeconds = config.periodSeconds;
      }
    }

    function AfterPodTemplateGeneration(pod) {
      var containers = pod.spec.containers;
      containers.forEach(addProbesForContainer)
      return pod;
    }
  configSchema:
    type: object
    properties:
      port:
        type: number
      initialDelaySeconds:
        type: number
      periodSeconds:
        type: number
      rpcTimeout:
        type: string
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: termination-grace
  namespace: kapp-hipster
spec:
  scope: application
  pluginName: termination-grace
  config:
    periodSeconds: 5
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: paymentservice
  namespace: kapp-hipster
spec:
  image: diveinto/paymentservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 50051
      servicePort: 50051
  env:
    - name: PORT
      value: "50051"
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: paymentservice-manually-scale
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  manually-scale
  componentName: paymentservice
  config:
    replicas: 2
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: paymentservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: paymentservice
  config:
    port: 50051
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: shippingservice
  namespace: kapp-hipster
spec:
  image: diveinto/shippingservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 50051
      servicePort: 50051
  env:
    - name: PORT
      value: "50051"
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: shippingservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: shippingservice
  config:
    port: 50051
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: currencyservice
  namespace: kapp-hipster
spec:
  image: diveinto/currencyservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 7000
      servicePort: 7000
  env:
    - name: PORT
      value: "7000"
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: currencyservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: currencyservice
  config:
    port: 7000
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: productcatalogservice
  namespace: kapp-hipster
spec:
  image: diveinto/productcatalogservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 3550
      servicePort: 3550
  env:
    - name: PORT
      value: "3550"
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: productcatalogservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: productcatalogservice
  config:
    port: 3550
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: adservice
  namespace: kapp-hipster
spec:
  image: diveinto/adservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  -  cpu: 150m
  - memory: 256Mi
  ports:
    - name: grpc
      containerPort: 9555
      servicePort: 9555
  env:
    - name: PORT
      value: "9555"
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_STATS
      value: "1"
    #- name: DISABLE_PROFILER
    #  value: "1"
    #- name: DISABLE_DEBUGGER
    #  value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: adservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: adservice
  config:
    port: 9555
    initialDelaySeconds: 20
    periodSeconds: 15
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: cartservice
  namespace: kapp-hipster
spec:
  image: diveinto/cartservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 7070
      servicePort: 7070
  env:
    - name: REDIS_ADDR
      value: redis/redis
      type: linked
    - name: PORT
      value: "7070"
    - name: LISTEN_ADDR
      value: "0.0.0.0"
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: cartservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: cartservice
  config:
    port: 7070
    initialDelaySeconds: 15
    periodSeconds: 10
    rpcTimeout: 5s
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: redis
  namespace: kapp-hipster
spec:
  image: redis:alpine
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: redis
      containerPort: 6379
      servicePort: 6379
  volumes:
    - path: /data
      type: emptyDir
      size: 128Mi
  command: ["redis-server"]
#  args: ["/usr/local/etc/redis/redis.conf"]
#  configs:
#    - paths:
#        - /redis/redis.conf
#      mountPath: /usr/local/etc/redis
    #   readinessProbe:
    #     periodSeconds: 5
    #     tcpSocket:
    #       port: 6379
    #   livenessProbe:
    #     periodSeconds: 5
    #     tcpSocket:
    #       port: 6379
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: checkoutservice
  namespace: kapp-hipster
spec:
  image: diveinto/checkoutservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 5050
      servicePort: 5050
  env:
    - name: PORT
      value: "5050"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: productcatalogservice/grpc
      type: linked
    - name: SHIPPING_SERVICE_ADDR
      value: shippingservice/grpc
      type: linked
    - name: PAYMENT_SERVICE_ADDR
      value: "paymentservice/grpc"
      type: linked
    - name: EMAIL_SERVICE_ADDR
      value: "emailservice/grpc"
      type: linked
    - name: CURRENCY_SERVICE_ADDR
      value: "currencyservice/grpc"
      type: linked
    - name: CART_SERVICE_ADDR
      value: "cartservice/grpc"
      type: linked
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: checkoutservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: checkoutservice
  config:
    port: 5050
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: frontend
  namespace: kapp-hipster
spec:
  image: diveinto/frontend:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 8080
      servicePort: 8080
  env:
    - name: PORT
      value: "8080"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "productcatalogservice/grpc"
      type: linked
    - name: CURRENCY_SERVICE_ADDR
      value: "currencyservice/grpc"
      type: linked
    - name: CART_SERVICE_ADDR
      value: "cartservice/grpc"
      type: linked
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "recommendationservice/grpc"
      type: linked
    - name: SHIPPING_SERVICE_ADDR
      value: "shippingservice/grpc"
      type: linked
    - name: CHECKOUT_SERVICE_ADDR
      value: "checkoutservice/grpc"
      type: linked
    - name: AD_SERVICE_ADDR
      value: "adservice/grpc"
      type: linked
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
    # - name: JAEGER_SERVICE_ADDR
    #   value: "jaeger-collector:14268"
    #   readinessProbe:
    #     initialDelaySeconds: 10
    #     httpGet:
    #       path: "/_healthz"
    #       port: 8080
    #       httpHeaders:
    #       - name: "Cookie"
    #         value: "shop_session-id=x-readiness-probe"
    #   livenessProbe:
    #     initialDelaySeconds: 10
    #     httpGet:
    #       path: "/_healthz"
    #       port: 8080
    #       httpHeaders:
    #       - name: "Cookie"
    #         value: "shop_session-id=x-liveness-probe"
    #   plugins:
    #     - name: ingress-hipster-frontend
    #       type: plugins.core.kapp.dev/v1alpha1.ingress
    #       hosts:
    #         - hipster.kapp.liumingmin.xyz
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: recommendationservice
  namespace: kapp-hipster
spec:
  image: diveinto/recommendationservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 8080
      servicePort: 8080
  env:
    - name: PORT
      value: "8080"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "productcatalogservice/grpc"
      type: linked
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
    - name: DISABLE_DEBUGGER
      value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: recommendationservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: recommendationservice
  config:
    periodSeconds: 5
    port: 8080
---
apiVersion: core.kapp.dev/v1alpha1
kind: Component
metadata:
  name: emailservice
  namespace: kapp-hipster
spec:
  image: diveinto/emailservice:v0.1.4-4-g997b5e8
  podAffinityType: prefer-fanout
  nodeSelectorLabels:
    kubernetes.io/os: linux
  cpu: 50m
  memory: 64Mi
  ports:
    - name: grpc
      containerPort: 5000
      servicePort: 8080
  env:
    - name: PORT
      value: "8080"
    - name: DISABLE_TRACING
      value: "1"
    - name: DISABLE_PROFILER
      value: "1"
---
apiVersion: core.kapp.dev/v1alpha1
kind: PluginBinding
metadata:
  name: emailservice-grpc-health-probe
  namespace: kapp-hipster
spec:
  scope: component
  pluginName:  grpc-health-probe
  componentName: emailservice
  config:
    periodSeconds: 5
    port: 8080
