apiVersion: core.kapp.dev/v1alpha1
kind: ApplicationPlugin
metadata:
  name: kapp-builtin-application-plugin-ingress
spec:
  src: |
    function AfterApplicationSaved() {
      __builtinApplicationPluginIngress();
    }
  configSchema:
    title: Ingress rules
    type: object
    required:
      - hosts
      - paths
    properties:
      hosts:
        type: array
        items:
          type: string
      httpsCert:
        type: string
      paths:
        type: array
        items:
          type: string
      stripPath:
        type: boolean
      destinations:
        type: array
        items:
          type: object
          properties:
            destination:
              type: string
            weight:
              type: number