apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    kalm-control-plane: "true"
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  values:
    global:
      proxy:
        holdApplicationUntilProxyStarts: true
  addonComponents:
    prometheus:
      enabled: true
  profile: default
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
    ingressGateways:
    - k8s:
        serviceAnnotations:
          "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istio-ingressgateway
              topologyKey: kubernetes.io/hostname
