# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/core.kapp.dev_components.yaml
- bases/core.kapp.dev_componentplugins.yaml
- bases/core.kapp.dev_componentpluginbindings.yaml
#- bases/core.kapp.dev_componenttemplates.yaml
#- bases/core.kapp.dev_dependencies.yaml
- bases/core.kapp.dev_httpscertissuers.yaml
- bases/core.kapp.dev_httpscerts.yaml
- bases/core.kapp.dev_dockerregistries.yaml
- bases/core.kapp.dev_httproutes.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_applications.yaml
#- patches/webhook_in_componenttemplates.yaml
#- patches/webhook_in_dependencies.yaml
#- patches/webhook_in_components.yaml
#- patches/webhook_in_applicationplugins.yaml
#- patches/webhook_in_applicationpluginbindings.yaml
#- patches/webhook_in_httpscertissuers.yaml
#- patches/webhook_in_httpscerts.yaml
#- patches/webhook_in_dockerregistries.yaml
#- patches/webhook_in_httproutes.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_applications.yaml
#- patches/cainjection_in_componenttemplates.yaml
#- patches/cainjection_in_dependencies.yaml
#- patches/cainjection_in_components.yaml
#- patches/cainjection_in_applicationplugins.yaml
#- patches/cainjection_in_applicationpluginbindings.yaml
#- patches/cainjection_in_httpscertissuers.yaml
#- patches/cainjection_in_httpscerts.yaml
#- patches/cainjection_in_dockerregistries.yaml
#- patches/cainjection_in_httproutes.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
