branches:
  only:
    - ci

git:
  depth: false

jobs:
  include:
    - language: go
      env:
        - GO111MODULE=on # remove this when change to golang 1.13
      go:
        - 1.12
      stage: test
      name: api
      before_install:
        - cd api
        - go get ./...
      script:
        - cd api
        - go test -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
    - language: go
      env:
        - GO111MODULE=on # remove this when change to golang 1.13
      go:
        - 1.12
      stage: test
      name: controller
      script:
        - cd controller
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
