branches:
  only:
    - ci

git:
  depth: false

jobs:
  include:
    - language: go
      env:
        - GO111MODULE=on # remove this when change to golang 1.13
        - KUBEBUILDER_ASSETS=$HOME/kubebuilder/bin
      go:
        - 1.12
      stage: test
      name: api
      before_install:
        - os=$(go env GOOS)
        - arch=$(go env GOARCH)
        - curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
        - sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} $HOME/kubebuilder
        - export PATH=$PATH:$HOME/kubebuilder/bin
      install:
        - cd api
        - go get ./...
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
          - $HOME/kubebuilder/bin
    - language: go
      env:
        - GO111MODULE=on # remove this when change to golang 1.13
        - KUBEBUILDER_ASSETS=$HOME/kubebuilder/bin
      go:
        - 1.12
      stage: test
      name: controller
      before_install:
        - os=$(go env GOOS)
        - arch=$(go env GOARCH)
        - curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
        - sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} $HOME/kubebuilder
        - export PATH=$PATH:$HOME/kubebuilder/bin
      install:
        - cd controller
        - go get ./...
        - which kubebuilder
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
          - $HOME/kubebuilder/bin
