git:
  depth: false

stages:
  - test
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master

before_install:
  - os=$(go env GOOS)
  - arch=$(go env GOARCH)
  - curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
  - sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} $HOME/kubebuilder
  - export PATH=$PATH:$HOME/kubebuilder/bin

jobs:
  include:
    - language: go
      go:
        - 1.13
      env:
        - KUBEBUILDER_ASSETS=$HOME/kubebuilder/bin
      stage: test
      name: api
      install:
        - cd api
        - go get ./...
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
    - language: go
      go:
        - 1.13
      env:
        - KUBEBUILDER_ASSETS=$HOME/kubebuilder/bin
      stage: test
      name: controller
      install:
        - cd controller
        - go get ./...
      script:
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
    - service:
        - docker
      stage: build
      name: controller
      language: go
      go:
        - 1.13
      install:
        - cd controller
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - make docker-build
        - make docker-push
    - service:
        - docker
      stage: build
      name: operator
      language: go
      go:
        - 1.13
      install:
        - cd operator
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - make docker-build
        - make docker-push
    - service:
        - docker
      stage: build
      name: dashboard
      install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build . -t kappstaging/dashboard:latest
        - docker push kappstaging/dashboard:latest
    - language: go
      go:
        - 1.13
      stage: deploy
      name: controller
      install:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.9/bin/linux/amd64/kubectl
        - chmod +x ./kubectl
        - sudo mv ./kubectl /usr/local/bin/kubectl
        - mkdir ${HOME}/.kube
        - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
      script:
        - cd controller
        - make deploy
        - kubectl -n kapp-system patch deployment kapp-controller -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
    - language: go
      go:
        - 1.13
      stage: deploy
      name: operator
      install:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.9/bin/linux/amd64/kubectl
        - chmod +x ./kubectl
        - sudo mv ./kubectl /usr/local/bin/kubectl
        - mkdir ${HOME}/.kube
        - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
      script:
        - cd operator
        - make deploy
        - kubectl -n kapp-operator patch deployment kapp-operator -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
    - language: go
      go:
        - 1.13
      stage: deploy
      name: dashboard
      install:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.9/bin/linux/amd64/kubectl
        - chmod +x ./kubectl
        - sudo mv ./kubectl /usr/local/bin/kubectl
        - mkdir ${HOME}/.kube
        - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
      script:
        - kubectl apply -f controller/config/samples/core_v1alpha1_application_kapp_dashboard.yaml
        - kubectl -n kapp-system patch deployment kapp-dashboard -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
