apiVersion: v1
kind: Namespace
metadata:
  name: kapp-kong
---
apiVersion: core.kapp.dev/v1alpha1
data: |
  # Prometheus metrics server
  server {
      server_name kong_prometheus_exporter;
      listen 0.0.0.0:9542; # can be any other port as well
      access_log off;

      location /metrics {
          default_type text/plain;
          content_by_lua_block {
               local prometheus = require "kong.plugins.prometheus.exporter"
               prometheus:collect()
          }
      }

      location /nginx_status {
          internal;
          stub_status;
      }
  }
  # Health check server
  server {
      server_name kong_health_check;
      listen 0.0.0.0:9001; # can be any other port as well

      access_log off;
      location /health {
        return 200;
      }
  }
kind: File
metadata:
  name: servers.conf
  namespace: kapp-kong
---
apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name: ingress-kong
  namespace: kapp-kong
spec:
  components:
    - name: proxy
      image: kong:1.4
      beforeDestroy:
        - /bin/sh
        - -c
        - kong quit
      volumeMounts:
        - mountPath: /kong/
          name: servers-conf
      resources:
        cpu:
          min: 500m
          max: 1000m
        memory:
          min: 500M
          max: 2G
      ports:
        - containerPort: 8000
          name: proxy
          protocol: TCP
          servicePort: 80
        - containerPort: 8443
          name: proxy-ssl
          protocol: TCP
          servicePort: 443
        - containerPort: 9542
          name: metrics
          protocol: TCP
          servicePort: 9542
      env:
        - name: KONG_DATABASE
          value: 'off'
        - name: KONG_NGINX_WORKER_PROCESSES
          value: '1'
        - name: KONG_NGINX_HTTP_INCLUDE
          value: /kong/servers.conf
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 127.0.0.1:8444 ssl
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000, 0.0.0.0:8443 ssl http2
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 9001
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 9001
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      securityContext:
        runAsUser: 1000
    - name: ingress-controller
      image: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.7.0
      args:
        - /kong-ingress-controller
        - --kong-url=https://localhost:8444
        - --admin-tls-skip-verify
        - --publish-service=kong/kong-proxy
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      ports:
        - containerPort: 8080
          name: webhook
          protocol: TCP
          servicePort: 8080
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 10254
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 10254
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
  volumes:
    - name: servers-conf
      configMap:
        name: servers.conf
