version: 2.1
description: |
  Help deploy Component in Kalm.
executors:
  default:
    description: |
      Docker image with curl
    docker:
    - image: tutum/curl:alpine
jobs:
  run:
    description: |
      Call deploy webhook of Kalm to trigger deploy of Component.
    executor: default
    parameters:
      KALM_API_ADDRESS:
        type: string
      KALM_DEPLOY_KEY:
        type: string
      KALM_APP:
        type: string
      KALM_COMPONENT:
        type: string
      KALM_COMPONENT_IMG_TAG:
        type: string
    steps:
    - run: curl -v -XPOST << parameters.KALM_API_ADDRESS >>/__kalm_webhook/deploy?deploy-key=<< parameters.KALM_DEPLOY_KEY >>\&app=<< parameters.KALM_APP >>\&component=<< parameters.KALM_COMPONENT >>\&image-tag=<< parameters.KALM_COMPONENT_IMG_TAG >>
