# permissions for end users to view acmeservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acmeserver-viewer-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - acmeservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - acmeservers/status
  verbs:
  - get
