# permissions to do edit applicationpluginbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationpluginbinding-editor-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - applicationpluginbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - applicationpluginbindings/status
  verbs:
  - get
  - patch
  - update
