# permissions to do edit applicationplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationplugin-editor-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - applicationplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - applicationplugins/status
  verbs:
  - get
  - patch
  - update
