# permissions to do viewer applicationpluginbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationpluginbinding-viewer-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - applicationpluginbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - applicationpluginbindings/status
  verbs:
  - get
