# permissions to do viewer applicationplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationplugin-viewer-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - applicationplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - applicationplugins/status
  verbs:
  - get
