# permissions for end users to edit clusterresourcequota.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterresourcequota-editor-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - clusterresourcequota
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - clusterresourcequota/status
  verbs:
  - get
