# permissions for end users to view clusterresourcequota.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterresourcequota-viewer-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - clusterresourcequota
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - clusterresourcequota/status
  verbs:
  - get
