# permissions to do edit componenttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componenttemplate-editor-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - componenttemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - componenttemplates/status
  verbs:
  - get
  - patch
  - update
