# permissions to do edit components.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: component-editor-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
