# permissions to do viewer componenttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: componenttemplate-viewer-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - componenttemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - componenttemplates/status
  verbs:
  - get
