# permissions to do viewer components.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: component-viewer-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - components
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - components/status
  verbs:
  - get
