# permissions to do edit dependencies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dependency-editor-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - dependencies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - dependencies/status
  verbs:
  - get
  - patch
  - update
