# permissions to do viewer dependencies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dependency-viewer-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - dependencies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - dependencies/status
  verbs:
  - get
