# permissions for end users to view deploykeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploykey-viewer-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - deploykeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - deploykeys/status
  verbs:
  - get
