# permissions to do edit dockerregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockerregistry-editor-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - dockerregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - dockerregistries/status
  verbs:
  - get
  - patch
  - update
