# permissions to do viewer dockerregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockerregistry-viewer-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - dockerregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - dockerregistries/status
  verbs:
  - get
