# permissions to do edit files.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: file-editor-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - files
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - files/status
  verbs:
  - get
  - patch
  - update
