# permissions to do viewer files.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: file-viewer-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - files
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - files/status
  verbs:
  - get
