# permissions to do edit httpscerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpscert-editor-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - httpscerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - httpscerts/status
  verbs:
  - get
  - patch
  - update
