# permissions to do edit httproutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproute-editor-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - httproutes/status
  verbs:
  - get
  - patch
  - update
