# permissions to do viewer httpscertissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpscertissuer-viewer-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - httpscertissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - httpscertissuers/status
  verbs:
  - get
