# permissions to do edit httpscertissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpscertissuer-editor-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - httpscertissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - httpscertissuers/status
  verbs:
  - get
  - patch
  - update
