# permissions to do edit plugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plugin-editor-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - plugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - plugins/status
  verbs:
  - get
  - patch
  - update
