# permissions to do viewer plugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plugin-viewer-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - plugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - plugins/status
  verbs:
  - get
