# permissions to do edit protectedendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: protectedendpoint-editor-role
rules:
- apiGroups:
  - core.kapp.dev
  resources:
  - protectedendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kapp.dev
  resources:
  - protectedendpoints/status
  verbs:
  - get
  - patch
  - update
