# permissions to do viewer singlesignonconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: singlesignonconfig-viewer-role
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - singlesignonconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kalm.dev
  resources:
  - singlesignonconfigs/status
  verbs:
  - get
