apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name: test
spec:
  components:
    - name: nginx
      image: nginx:alpine
      env:
        - name: a
          value: b
        - name: x
          value: z
      plugins:
        - name: manual-scaler
          replicas: 2

