apiVersion: core.kapp.dev/v1alpha1
kind: ComponentTemplate
metadata:
  name: componenttemplate-sample
spec:
  # Add fields here
  name: web
  image: nginx:alpine
  workloadType: server
  beforeStart:
    - ls -alh /
    - echo "test" > /tmp/bbq
    - ls -alh /tmp
  afterStart:
    - ls -alh /tmp/
  beforeDestroy:
    - echo "Bye Bye"
  env:
    # Get value of another component export port address,
    # It will be helpful is the component depends on another.
    - name: API_URL
      type: linked
    # Get value from shareEnv
    - name: SOME_COMMON_ENV
      type: external
    # normal env definition
    - name: SOME_ENV
      type: static
      value: SOME_VALUE
  ports:
    - name: http
      protocol: TCP
      containerPort: 80
      servicePort: 80
  cpu: 100m
  memory: 500m
  #        disk:
  #          - path: /a/b/c
  #            name: tmpfile
  #            size: 1G
  #            storageClass: ssd
  volumeMounts:
    - mountPath: /tmp/
      name: nginx-config
