apiVersion: core.kapp.dev/v1alpha1
kind: Dependency
metadata:
  name: dependency-sample-kong
spec:
  # Add fields here
  type: kong
  version: 1.0.0
  config:
      cert-manager: dependency-sample-cert-manager
---
apiVersion: core.kapp.dev/v1alpha1
kind: Dependency
metadata:
  name: dependency-sample-cert-manager
spec:
  type: cert-manager
  version: 1.0.0
  config:
    tlsType: acme
    challengeProvider: cloudflare
    challengeEmail: diveintotomorrow@gmail.com
    challengeSecret: 38f17393420aab873a6e74f2aabfb65a43ec4
