apiVersion: core.kapp.dev/v1alpha1
kind: ComponentTemplate
metadata:
  name: componenttemplate-sample
spec:
  # Add fields here
  name: web
  image: nginx:alpine
  beforeStart:
    - ls -alh /
    - echo "test" > /tmp/bbq
    - ls -alh /tmp
  afterStart:
    - ls -alh /tmp/
  beforeDestroy:
    - echo "Bye Bye"
  env:
    # Get value of another component export port address,
    # It will be helpful is the component depends on another.
    - name: API_URL
      componentPort: api/http
      prefix: http://
      suffix: /v4
    # Get value from shareEnv
    - name: SOME_COMMON_ENV
      sharedEnv: SOME_COMMON_ENV
    # normal env definition
    - name: SOME_ENV
      value: SOME_VALUE
  ports:
    - name: http
      containerPort: 80
      servicePort: 80
  resources:
    cpu:
      min: 10m
      max: 100m
    memory:
      min: 500M
      max: 2G
  #        disk:
  #          - path: /a/b/c
  #            name: tmpfile
  #            size: 1G
  #            storageClass: ssd
  volumeMounts:
    - mountPath: /tmp/
      name: nginx-config
