apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name: test
spec:
  components:
    - name: nginx
      image: nginx:alpine
      plugins:
        - name: manual-scaler
          replicas: 3

