apiVersion: v1
kind: Namespace
metadata:
  name: kapp-test
---
apiVersion: core.kapp.dev/v1alpha1
kind: File
metadata:
  name: nginx-config
  namespace: kapp-test
data: |
  location / {
    proxy_pass http://localhost:3000
  }
---
apiVersion: core.kapp.dev/v1alpha1
kind: Application
metadata:
  name: test
  namespace: kapp-test
spec:
  components:
    - name: api
      image: nginx:alpine
      env:
        - name: DB_URL
          value: postgres://user:password@test.dev:5432/db_name
        - name: SOME_ENV
          value: SOME_VALUE
      ports:
        - containerPort: 3000
          servicePort: 80
          name: http
      plugins:
        - name: manual-scaler
          replicas: 1
    - name: web
      image: nginx:alpine
      beforeStart:
        - ls -alh /
        - echo "test" > /tmp/bbq
        - ls -alh /tmp
      afterStart:
        - ls -alh /tmp/
      beforeDestroy:
        - echo "Bye Bye"
      env:
        # Get value of another component export port address,
        # It will be helpful is the component depends on another.
        - name: API_URL
          componentPort: api/http
          prefix: http://
          suffix: /v4
        # Get value from shareEnv
        - name: SOME_COMMON_ENV
          sharedEnv: SOME_COMMON_ENV
        # normal env definition
        - name: SOME_ENV
          value: SOME_VALUE
      ports:
        - name: http
          containerPort: 80
          servicePort: 80
      resources:
        cpu:
          min: 10m
          max: 100m
        memory:
          min: 500M
          max: 2G
      #        disk:
      #          - path: /a/b/c
      #            name: tmpfile
      #            size: 1G
      #            storageClass: ssd
      volumeMounts:
        - mountPath: /tmp/
          name: nginx-config
      plugins:
        - name: manual-scaler
          type: plugins.core.kapp.dev/v1alpha1.manual-scaler
          replicas: 1
        # It's allowed to use a plugin more than one time
        - name: ingress-root
          type: plugins.core.kapp.dev/v1alpha1.ingress
          enableHttps: true
          enableHttp: true
          # require enabledHttps and enableHttp are all true
          autoHttps: true
          hosts:
            - www.example.com
            - www.example.io
          path:
            - /
          stripPath: true
          preserveHost: true
        - name: ingress-legacy
          type: plugins.core.kapp.dev/v1alpha1.ingress
          hosts:
            - www.example.global
          path:
            - /
          stripPath: false
          preserveHost: false

  sharedEnv:
    - name: SOME_COMMON_ENV
      value: shared_value
  volumes:
    - configMap:
        name: nginx-config
      name: nginx-config
