apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kalm-operator:psp:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:psp:privileged
subjects:
  - kind: ServiceAccount
    name: kalm-operator
    namespace: kalm-operator
