# permissions to do viewer kappoperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kappoperatorconfig-viewer-role
rules:
- apiGroups:
  - install.kapp.dev
  resources:
  - kappoperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - install.kapp.dev
  resources:
  - kappoperatorconfigs/status
  verbs:
  - get
