# permissions to do edit kalmoperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kalmoperatorconfig-editor-role
rules:
- apiGroups:
  - install.kalm.dev
  resources:
  - kalmoperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.kalm.dev
  resources:
  - kalmoperatorconfigs/status
  verbs:
  - get
  - patch
  - update
