apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: kapp-monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: kapp-monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  retention: 30d
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
# storage:
#   volumeClaimTemplate:
#     metadata:
#         creationTimestamp: "2006-01-02T15:04:05Z"
#     apiVersion: v1
#     kind: PersistentVolumeClaim
#     spec:
#       accessModes:
#       - ReadWriteOnce
#       resources:
#         requests:
#           storage: KAPP-PROMETHEUS-STORAGE-PLACEHOLDER
#       storageClassName: standard
  version: v2.11.0
