apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: operator
  name: operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    control-plane: operator
spec:
  selector:
    matchLabels:
      control-plane: operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: operator
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: quay.io/kalmhq/kalm-operator:latest
          imagePullPolicy: Always
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
