# DASHBOARD_DOMAIN_PLACEHOLDER
# TMP_ADMIN_EMAIL_PLACEHOLDER
# USER_ID_PLACEHOLDER
apiVersion: core.kalm.dev/v1alpha1
kind: SingleSignOnConfig
metadata:
  name: sso
  namespace: kalm-system
spec:
  domain: DASHBOARD_DOMAIN_PLACEHOLDER
  idTokenExpirySeconds: 300
  temporaryUser:
    email: TMP_ADMIN_EMAIL_PLACEHOLDER
    passwordHash: $2a$12$EwfAkgwdXptOuETVkt327OfPvMBGrmiCZQ7S1U9Rp19QSp2ZsEYsS
    userId: USER_ID_PLACEHOLDER
    username: admin
---
apiVersion: core.kalm.dev/v1alpha1
kind: HttpRoute
metadata:
  name: kalm-route
spec:
  destinations:
  - host: kalm.kalm-system.svc.cluster.local:80
    weight: 1
  hosts:
  - DASHBOARD_DOMAIN_PLACEHOLDER
  httpRedirectToHttps: false
  methods:
  - GET
  - HEAD
  - POST
  - PUT
  - PATCH
  - DELETE
  - OPTIONS
  - TRACE
  - CONNECT
  paths:
  - /
  schemes:
  - https
  - http
---
apiVersion: core.kalm.dev/v1alpha1
kind: ProtectedEndpoint
metadata:
  name: component-kalm
  namespace: kalm-system
spec:
  allowToPassIfHasBearerToken: true
  name: kalm
  ports:
  - 3001
---
apiVersion: core.kalm.dev/v1alpha1
kind: RoleBinding
metadata:
  name: manually-created-cluster-owner-for-USER_ID_PLACEHOLDER
  namespace: kalm-system
spec:
  creator: kubectl
  role: clusterOwner
  subject: TMP_ADMIN_EMAIL_PLACEHOLDER
  subjectType: user
