resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patchesJson6902:
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
  path: patch.yaml
