# install OperatorResource to install:
# - cert-manager
# - istio
# - Kalm CRD & Roles
# - Kalm controller
# - Kalm dashboard
apiVersion: v1
kind: Namespace
metadata:
  name: kapp-operator
---
apiVersion: install.kapp.dev/v1alpha1
kind: KappOperatorConfig
metadata:
  namespace: kapp-operator
  name: kappoperatorconfig-sample
