apiVersion: v1
kind: Namespace
metadata:
  name: kapp-operator
---
apiVersion: install.kapp.dev/v1alpha1
kind: KappOperatorConfig
metadata:
  namespace: kapp-operator
  name: kappoperatorconfig-sample
spec:
  skipKappControllerInstallation: true
