---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kalm-api-app-viewer
rules:
- apiGroups:
  - core.kalm.dev
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kalm-api-viewer-role-binding
  namespace: sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kalm-api-app-viewer
subjects:
- kind: ServiceAccount
  name: default
  namespace: sandbox
