# https://github.com/marketplace/actions/build-and-push-docker-images#usage

name: build & push img with cache

on:
  push:
    branches: 
      - master
      - ci

jobs:
  job-build-with-cache:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - 
      #   uses: actions/checkout@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.npm
          #key: ${{ runner.os }}-buildx-${{ hashFiles('**/package-lock.json') }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_TMP_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TMP_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: diveinto/kalm-for-test:latest
          cache-from: type=local,src=~/.npm
          cache-to: type=local,dest=~/.npm
      - 
        name: list dir
        run: ls -al ~/* 
      - 
        name: list dir2  
        run: ls -al * 