name: Call Kalm Deploy Webhook

on:
  push:
    branches:
      - master
      - github-action

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: A job to deploy new Kalm Component
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Deploy Action
        uses: kalmhq/kalm-deploy-action@v0.0.4 # Uses public action
        id: deploy
        with:
          KALM_API_ADDRESS: ${{ secrets.KALM_API_ADDRESS }}
          KALM_DEPLOY_KEY: ${{ secrets.KALM_DEPLOY_KEY }}
          KALM_APP: kalm-system
          KALM_COMPONENT: kalm
          KALM_COMPONENT_IMG_TAG: latest
      - name: output of step deploy
        run: echo 'The callback response was ${{ steps.deploy.outputs.resp }}.'  