apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    control-plane: controller
spec:
  selector:
    matchLabels:
      control-plane: controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: kapp/controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        env:
          - name: ENABLE_WEBHOOKS
            value: "true"
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      terminationGracePeriodSeconds: 10
